Support for multiple files transfer
sdushantha/qr-filetransfer pull request #46
Opened 2020-09-21 17:26 UTC by puneethkanna

2020-09-21 17:27 UTC, puneethkanna commented
Multiple files will be zipped with the name qr_filetransfer and it will be deleted after the closing of session.

2020-09-22 06:34 UTC, npes87184 commented
Hi, I will find time to review and test it. Thank you. 👍

2020-09-24 07:13 UTC, puneethkanna commented
> Hi, I will find time to review and test it. Thank you. +1

Any bugs detected?

2020-09-25 03:31 UTC, npes87184 commented
Sorry for the late reply. I am busy recently specific in weekdays. I will check this PR in this weekend if possible. Thank you for your patient.

2020-09-27 01:21 UTC, npes87184 requested changes
Also the two commits should be squashed to one. Because they are doing the same thing.

Thank you! 👍

2020-09-27 01:21 UTC, npes87184 commented on qr_filetransfer/qr_filetransfer.py
> +        with ZipFile(zip_name, 'w') as zipObj2:
`NameError: name 'ZipFile' is not defined`

Miss this line `from zipfile import *` ?

2020-09-27 01:21 UTC, npes87184 commented on qr_filetransfer/qr_filetransfer.py
> +        # Getting the last file abs_path and removing the name and concatinating with the zip_name
Trailing space

2020-09-27 01:21 UTC, npes87184 commented on qr_filetransfer/qr_filetransfer.py
> +    if type(file_path) is list and len(file_path) > 1:
I recommend use `if`, `elif` and `else` to chain there three cases.

2020-09-27 01:21 UTC, npes87184 commented on qr_filetransfer/qr_filetransfer.py
> +        delete_zip = file_path
If we chain the `if`, `elif` and `else`. 

The part
```
        abs_path = os.path.normpath(os.path.abspath(zip_name))
        file_dir = os.path.dirname(abs_path)
        file_path = os.path.basename(abs_path)
        file_path = file_path.replace(file_path, zip_name)

        delete_zip = file_path
```

can be simply changed to

```
        file_path = zip_name
        delete_zip = zip_name
```

2020-09-27 01:21 UTC, npes87184 commented on qr_filetransfer/qr_filetransfer.py
>      file_path = file_path.replace(" ", "%20")
I recommend change the name of this variable. It is very confusing with the input.

2020-09-27 05:02 UTC, puneethkanna commented on qr_filetransfer/qr_filetransfer.py
> +        with ZipFile(zip_name, 'w') as zipObj2:
Thanks!. I forgot to include it.

2020-09-27 05:03 UTC, puneethkanna commented on qr_filetransfer/qr_filetransfer.py
> +        # Getting the last file abs_path and removing the name and concatinating with the zip_name
Trailing space means , I need to include a space at End of Line or remove the space.

2020-09-27 05:16 UTC, puneethkanna commented on qr_filetransfer/qr_filetransfer.py
> +        delete_zip = file_path
But we will not get the abs path from this.

2020-09-27 05:17 UTC, puneethkanna commented on qr_filetransfer/qr_filetransfer.py
> +    if type(file_path) is list and len(file_path) > 1:
Sure, I will modify this.

2020-09-27 05:20 UTC, puneethkanna commented on qr_filetransfer/qr_filetransfer.py
>      file_path = file_path.replace(" ", "%20")
I want to change the file_path  -> files_path_list.
Is this name okay.

2020-09-27 10:00 UTC, npes87184 commented on qr_filetransfer/qr_filetransfer.py
> +        # Getting the last file abs_path and removing the name and concatinating with the zip_name
remove the space.

2020-09-28 16:20 UTC, puneethkanna commented on qr_filetransfer/qr_filetransfer.py
>      file_path = file_path.replace(" ", "%20")
Please suggest a name. If I change a name it will impact the whole code.
I want to change  **file_path -> files_path_list**, What do you say?

2020-09-29 08:05 UTC, npes87184 commented on qr_filetransfer/qr_filetransfer.py
>      file_path = file_path.replace(" ", "%20")
The meaning of `file_path` here is the download target. Maybe something likes `download_target_path`? : \

2020-09-30 05:13 UTC, puneethkanna commented on qr_filetransfer/qr_filetransfer.py
>      file_path = file_path.replace(" ", "%20")
Okay!

2020-10-02 06:23 UTC, closed without merging

2020-10-02 06:23 UTC, puneethkanna commented
I am getting errors while squashing the commits, so I am opening a new pull request